### ISSUE TITLE
Github project

### ISSUE THREAD

**Issue by JustoRago** [ndorrh/FinalCapstoneJavascript#21]
[Project link](https://github.com/ndorrh/FinalCapstoneJavascript/projects/1)

This is a team of two students.

**Comment by leonardodiasb** [comment]
# Status: ✔️ Project Approved ✔️ 

Hi @asdt560,

Everything is looking great! Please, start your capstone :shipit:
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
